'use strict';
// Build ONE consolidated library of all functions + code: library/<subsystem>.md (record + inline raw
// decompile per function) + library/LIBRARY.md master index. Regenerable; stays in sync with the corpus.
const fs = require('fs');
const path = require('path');
const ROOT = path.resolve(__dirname, '../..');
const LIB = path.join(ROOT, 'library');
fs.mkdirSync(LIB, { recursive: true });
const fns = JSON.parse(fs.readFileSync(path.join(ROOT, 'indexes/functions.json'), 'utf8'));
const read = (rel) => { try { return fs.readFileSync(path.join(ROOT, rel), 'utf8'); } catch { return null; } };

// group by subsystem, sorted by address
const bySub = {};
for (const f of fns) (bySub[f.subsystem] = bySub[f.subsystem] || []).push(f);
for (const s of Object.keys(bySub)) bySub[s].sort((a, b) => a.address.localeCompare(b.address));

let masterRows = '';
let totalBytes = 0;
for (const [sub, list] of Object.entries(bySub).sort()) {
  let out = `# Library — ${sub}  (${list.length} functions)\n\n`;
  out += `_All ${sub} functions: reconstructed record + inline raw decompile. Generated by gen-library.js._\n\n`;
  out += `[← LIBRARY index](LIBRARY.md)\n\n`;
  // per-subsystem TOC
  out += list.map(f => `- [${f.address} ${f.resolved_name || f.name}](#${f.address.replace('0x', '')}) — ${f.status}/${f.confidence}`).join('\n') + '\n\n---\n\n';
  for (const f of list) {
    const anchor = f.address.replace('0x', '');
    out += `<a id="${anchor}"></a>\n\n`;
    const rec = f.doc_path ? read(f.doc_path) : null;
    if (rec) {
      out += rec.trim() + '\n\n';
    } else {
      out += `## ${f.address} ${f.resolved_name || f.name}\n\n(no record — thunk/${f.subsystem})\n\n`;
    }
    const raw = f.raw_path ? read(f.raw_path) : null;
    if (raw) {
      // For overlay records the raw already includes FUNCTION/CALLERS/CALLEES header; keep as-is.
      out += `### Raw decompile (inline) — \`${f.raw_path}\`\n\n\`\`\`c\n${raw.trim()}\n\`\`\`\n\n`;
    }
    out += `[↑ ${sub} top](#library--${sub}--${list.length}-functions) · [LIBRARY](LIBRARY.md)\n\n---\n\n`;
  }
  const file = path.join(LIB, `${sub}.md`);
  fs.writeFileSync(file, out);
  totalBytes += out.length;
  masterRows += `- **[${sub}](${sub}.md)** — ${list.length} functions (${(out.length / 1024).toFixed(0)} KB)\n`;
}

// master index: links to subsystem volumes + a flat all-function anchor table
let master = `# LIBRARY — consolidated network function + code library\n\n`;
master += `One browsable library of **all ${fns.length} functions**: each entry has its reconstructed record\n(behavior, I/O, side-effects, branches, corrected pseudocode, evidence) **and** its inline raw decompile.\nOrganized into subsystem volumes. For machine queries use \`../indexes/functions.json\` or \`re.js search\`.\n\n`;
master += `## Volumes\n${masterRows}\n`;
master += `## All functions (address → volume#anchor)\n\n| Address | Name | Subsystem | Status | Conf | Open |\n|---|---|---|---|---|---|\n`;
for (const f of fns.sort((a, b) => a.address.localeCompare(b.address)))
  master += `| ${f.address} | ${f.resolved_name || f.name} | ${f.subsystem} | ${f.status} | ${f.confidence} | [↗](${f.subsystem}.md#${f.address.replace('0x', '')}) |\n`;
fs.writeFileSync(path.join(LIB, 'LIBRARY.md'), master);

console.log(`library: ${Object.keys(bySub).length} volumes, ${fns.length} functions, ${(totalBytes / 1048576).toFixed(1)} MB total`);
