'use strict';
// re.js — corpus query + index-generation + completeness-gate CLI for the network RE corpus.
// Usage:
//   node re.js search --addr 0x005bb4d0 | --name FUN_005b | --subsystem rooms | --status inventoried
//                     --confidence Confirmed | --opcode 0x06 | --caller FUN_.. | --callee FUN_..
//   node re.js coverage        # regenerate COVERAGE.md from functions.json + record files
//   node re.js gen-index       # regenerate MASTER_INDEX.md from functions.json
//   node re.js validate        # completion-gate check: every inventoried fn has status+doc; report gaps
const fs = require('fs');
const path = require('path');
const ROOT = path.resolve(__dirname, '../..');
const IDX = path.join(ROOT, 'indexes');
const load = (f) => JSON.parse(fs.readFileSync(path.join(IDX, f), 'utf8'));
const fns = () => load('functions.json');

function arg(k) { const i = process.argv.indexOf('--' + k); return i >= 0 ? process.argv[i + 1] : null; }

const cmd = process.argv[2];
if (cmd === 'search') {
  let r = fns();
  const addr = arg('addr'); if (addr) r = r.filter(f => f.address === addr.toLowerCase());
  const name = arg('name'); if (name) r = r.filter(f => (f.name || '').includes(name) || (f.resolved_name || '').includes(name));
  const sub = arg('subsystem'); if (sub) r = r.filter(f => f.subsystem === sub);
  const st = arg('status'); if (st) r = r.filter(f => f.status === st);
  const cf = arg('confidence'); if (cf) r = r.filter(f => f.confidence === cf);
  const op = arg('opcode'); if (op) r = r.filter(f => (f.opcodes || []).includes(op));
  const caller = arg('caller'); if (caller) r = r.filter(f => (f.callers || []).some(c => c.includes(caller)));
  const callee = arg('callee'); if (callee) r = r.filter(f => (f.callees || []).some(c => c.includes(callee)));
  console.log(`${r.length} match(es)`);
  for (const f of r.slice(0, 200)) console.log(`${f.address}  ${f.subsystem.padEnd(14)} ${f.status.padEnd(12)} ${f.confidence.padEnd(10)} ${f.resolved_name || f.name}  ${f.doc_path || ''}`);
  if (r.length > 200) console.log(`... +${r.length - 200} more`);
} else if (cmd === 'coverage') {
  const r = fns();
  const by = (k) => r.reduce((a, f) => (a[f[k]] = (a[f[k]] || 0) + 1, a), {});
  const total = r.length;
  const netRel = r.filter(f => !['unrelated'].includes(f.subsystem)).length;
  const done = r.filter(f => f.status === 'reconstructed' || f.status === 'documented').length;
  const classified = r.filter(f => f.status !== 'inventoried').length;
  const rt = r.filter(f => f.runtime_validated).length;
  let md = `# COVERAGE — network RE corpus\n\n_Auto-generated by \`re.js coverage\`. Do not hand-edit._\n\n`;
  md += `## Functions\n`;
  md += `- Total inventoried: **${total}** (overlay-3dat ${by('module')['overlay-3dat']||0}, main-ee ${by('module')['main-ee']||0})\n`;
  md += `- Classified (status != inventoried): **${classified}** (${(classified/total*100).toFixed(1)}%)\n`;
  md += `- Fully reconstructed/documented: **${done}** (${(done/total*100).toFixed(1)}%)\n`;
  md += `- Runtime-validated: **${rt}**\n`;
  md += `- Missing raw decompile: **${r.filter(f=>!f.raw_path).length}**\n\n`;
  md += `## By status\n` + Object.entries(by('status')).sort().map(([k,v])=>`- ${k}: ${v}`).join('\n') + '\n\n';
  md += `## By subsystem\n` + Object.entries(by('subsystem')).sort().map(([k,v])=>`- ${k}: ${v}`).join('\n') + '\n\n';
  md += `## By confidence\n` + Object.entries(by('confidence')).sort().map(([k,v])=>`- ${k}: ${v}`).join('\n') + '\n\n';
  md += `## Derived indexes\n`;
  for (const j of ['packets.json','menus.json','structures.json','globals.json','strings.json','cross_references.json']) {
    let n = 0; try { n = load(j).length ?? Object.keys(load(j)).length; } catch {}
    md += `- ${j}: ${n} entries\n`;
  }
  fs.writeFileSync(path.join(ROOT, 'COVERAGE.md'), md);
  console.log(md);
} else if (cmd === 'gen-index') {
  const r = fns();
  let md = `# MASTER_INDEX — every network function\n\n_Auto-generated by \`re.js gen-index\` from indexes/functions.json._\n\n`;
  md += `| Address | Name | Resolved | Module | Subsystem | Status | Conf | Doc |\n|---|---|---|---|---|---|---|---|\n`;
  for (const f of r) md += `| ${f.address} | ${f.name} | ${f.resolved_name||''} | ${f.module} | ${f.subsystem} | ${f.status} | ${f.confidence} | ${f.doc_path?`[md](${f.doc_path})`:''} |\n`;
  fs.writeFileSync(path.join(ROOT, 'MASTER_INDEX.md'), md);
  console.log(`MASTER_INDEX.md: ${r.length} rows`);
} else if (cmd === 'validate') {
  const r = fns();
  const noStatus = r.filter(f => !f.status);
  const classifiedNoDoc = r.filter(f => f.status !== 'inventoried' && f.subsystem !== 'unrelated' && !f.doc_path);
  const noRaw = r.filter(f => !f.raw_path);
  console.log(`GATE CHECK:`);
  console.log(`  functions without status: ${noStatus.length}`);
  console.log(`  net-related & classified but NO doc record: ${classifiedNoDoc.length}`);
  console.log(`  still inventoried (unclassified): ${r.filter(f=>f.status==='inventoried').length}`);
  console.log(`  missing raw decompile: ${noRaw.length}`);
  process.exit(classifiedNoDoc.length === 0 && noStatus.length === 0 ? 0 : 1);
} else {
  console.log('usage: re.js search|coverage|gen-index|validate  (see header)');
}
