[Service]
Environment=SNAP_CMD0C_SELECTOR12=1
Environment=SNAP_RENDER2=0
Environment=SNAP_ROOM_RENDER=0
Environment=SNAP_ROOM_RENDER_A0=0
Environment=SNAP_ROOM_QUERY_REPLY=0
Environment=SNAP_ROOM_PUSH=0
Environment=SNAP_CMD0C_TEST=0